version: '2'
services:
  web:
    build: .
    network_mode: "bridge"
    ports:
      - "8099:80"
    volumes:
      - ./default.conf:/etc/nginx/sites-available/default.conf:ro
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./vars.ini:/usr/local/etc/php/conf.d/docker-vars.ini:ro
