version: '2'
services:
  web:
    build: .
    network_mode: "bridge"
    links:
      - "mysql"
    ports:
      - "8091:80"
  mysql:
    image: mysql:8.0.3
    network_mode: "bridge"
    volumes:
      - ./A2-Practice1.sql:/docker-entrypoint-initdb.d/A2-Practice1.sql:ro
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=A2-Practice1
